#!/bin/sh

#
# Test that starting up an Erlang/OTP release that's underneath a directory works
#

$CAT >$CMDLINE_FILE <<EOF
-v
EOF

RELEASE_PATH=$WORK/srv/erlang/myrelease/releases/0.0.1
$MKDIR -p $RELEASE_PATH
$TOUCH $RELEASE_PATH/test.boot
$TOUCH $RELEASE_PATH/sys.config
$TOUCH $RELEASE_PATH/vm.args
$MKDIR -p $WORK/srv/erlang/decoydir  # no release in here

$CAT >$EXPECTED <<EOF
erlinit: cmdline argc=2, merged argc=2
erlinit: merged argv[0]=/sbin/erlinit
erlinit: merged argv[1]=-v
erlinit: set_ctty
erlinit: find_erts_directory
erlinit: find_erts_library_directory
erlinit: directory /usr/lib/erlang/lib not found?
erlinit: find_release
erlinit: Using release in /srv/erlang/myrelease/releases/0.0.1.
erlinit: find_sys_config
erlinit: find_vm_args
erlinit: find_boot_path
erlinit: setup_environment
erlinit: setup_networking
erlinit: configure_hostname
erlinit: /etc/hostname not found
erlinit: Env: 'HOME=/root'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/srv/erlang/myrelease'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erl'
erlinit: Arg: 'erlexec'
erlinit: Arg: '-config'
erlinit: Arg: '/srv/erlang/myrelease/releases/0.0.1/sys.config'
erlinit: Arg: '-boot'
erlinit: Arg: '/srv/erlang/myrelease/releases/0.0.1/test'
erlinit: Arg: '-args_file'
erlinit: Arg: '/srv/erlang/myrelease/releases/0.0.1/vm.args'
erlinit: Launching erl...
Hello from erlexec
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: unmount_all
EOF
