#!/bin/sh

#
# Test that requesting that strace be run does the right thing
#

$CAT >$CONFIG <<EOF
-v

# Call strace and follow child processes
-s "/usr/bin/strace -f"
EOF

$CAT >$WORK/usr/bin/strace <<EOF
#!/bin/sh

echo Hello from strace 1>&2
EOF

$CAT >$EXPECTED <<EOF
erlinit: cmdline argc=1, merged argc=4
erlinit: merged argv[0]=/sbin/erlinit
erlinit: merged argv[1]=-v
erlinit: merged argv[2]=-s
erlinit: merged argv[3]=/usr/bin/strace -f
erlinit: set_ctty
erlinit: find_erts_directory
erlinit: find_erts_library_directory
erlinit: directory /usr/lib/erlang/lib not found?
erlinit: find_release
erlinit: No release found in /srv/erlang.
erlinit: setup_environment
erlinit: setup_networking
erlinit: configure_hostname
erlinit: /etc/hostname not found
erlinit: Env: 'HOME=/root'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/usr/lib/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erl'
erlinit: Arg: '/usr/bin/strace'
erlinit: Arg: '-f'
erlinit: Arg: '/usr/lib/erlang/erts-6.0/bin/erlexec'
erlinit: Launching erl...
Hello from strace
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: unmount_all
EOF
