#!/bin/sh

#
# Test that specifying --verbose on the command line works
#

$CAT >$CMDLINE_FILE <<EOF
--verbose
EOF

$CAT >$EXPECTED <<EOF
erlinit: cmdline argc=2, merged argc=2
erlinit: merged argv[0]=/sbin/erlinit
erlinit: merged argv[1]=--verbose
erlinit: set_ctty
erlinit: find_erts_directory
erlinit: find_erts_library_directory
erlinit: directory /usr/lib/erlang/lib not found?
erlinit: find_release
erlinit: No release found in /srv/erlang.
erlinit: setup_environment
erlinit: setup_networking
erlinit: configure_hostname
erlinit: /etc/hostname not found
erlinit: Env: 'HOME=/root'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/usr/lib/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erl'
erlinit: Arg: 'erlexec'
erlinit: Launching erl...
Hello from erlexec
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: unmount_all
EOF
