#!/bin/sh

#
# Test that calling out to a unique id generator does the right thing
#

cat >"$CONFIG" <<EOF
-v

# Specify a hostname pattern that has a unique id part
--hostname-pattern nerves-%.4s

# Call out to a dummy unique id generator
--uniqueid-exec "/usr/bin/make-unique-id"
EOF

cat >"$WORK/usr/bin/make-unique-id" <<EOF
#!/bin/sh

echo "0042"
EOF
chmod +x "$WORK/usr/bin/make-unique-id"

cat >"$EXPECTED" <<EOF
erlinit: cmdline argc=1, merged argc=6
erlinit: merged argv[0]=/sbin/init
erlinit: merged argv[1]=-v
erlinit: merged argv[2]=--hostname-pattern
erlinit: merged argv[3]=nerves-%.4s
erlinit: merged argv[4]=--uniqueid-exec
erlinit: merged argv[5]=/usr/bin/make-unique-id
fixture: mount("proc", "/proc", "proc", 14, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mkdir("/dev/pts", 755)
fixture: mkdir("/dev/shm", 1777)
fixture: mount("devpts", "/dev/pts", "devpts", 10, data)
fixture: symlink("/dev/mmcblk0","/dev/rootdisk0")
fixture: symlink("/dev/mmcblk0p4","/dev/rootdisk0p4")
fixture: symlink("/dev/mmcblk0p3","/dev/rootdisk0p3")
fixture: symlink("/dev/mmcblk0p2","/dev/rootdisk0p2")
fixture: symlink("/dev/mmcblk0p1","/dev/rootdisk0p1")
erlinit: set_ctty
fixture: setsid()
fixture: mount("tmpfs", "/tmp", "tmpfs", 14, data)
fixture: mount("tmpfs", "/run", "tmpfs", 14, data)
erlinit: find_release
erlinit: No release found in /srv/erlang.
erlinit: find_erts_directory
erlinit: setup_environment
erlinit: setup_networking
fixture: ioctl(SIOCGIFFLAGS)
fixture: ioctl(SIOCSIFFLAGS)
fixture: ioctl(SIOCGIFINDEX)
erlinit: configure_hostname
erlinit: system_cmd '/usr/bin/make-unique-id'
erlinit: Hostname: nerves-0042
fixture: sethostname("nerves-0042", 11)
erlinit: Env: 'HOME=/home/user0'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/usr/lib/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erlexec'
erlinit: Arg: 'erlexec'
erlinit: Arg: '-boot_var'
erlinit: Arg: 'RELEASE_LIB'
erlinit: Arg: '/srv/erlang/lib'
erlinit: Launching erl...
Hello from erlexec
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: Sending SIGTERM to all processes
fixture: kill(-1, 15)
fixture: sleep(1)
erlinit: Sending SIGKILL to all processes
fixture: kill(-1, 9)
erlinit: unmount_all
erlinit: unmounting tmpfs at /sys/fs/cgroup...
fixture: umount("/sys/fs/cgroup")
erlinit: unmounting tmpfs at /dev/shm...
fixture: umount("/dev/shm")
erlinit: unmounting devpts at /dev/pts...
fixture: umount("/dev/pts")
erlinit: unmounting proc at /proc...
fixture: umount("/proc")
erlinit: unmounting sysfs at /sys...
fixture: umount("/sys")
EOF
