#!/bin/sh

#
# Test that calling out to a unique id generator does the right thing
#

$CAT >$CONFIG <<EOF
-v

# Specify a hostname pattern that has a unique id part
--hostname-pattern nerves-%.4s

# Call out to a dummy unique id generator
--uniqueid-exec "/usr/bin/make-unique-id"
EOF

$CAT >$WORK/usr/bin/make-unique-id <<EOF
#!/bin/sh

echo "0042"
EOF

$CAT >$EXPECTED <<EOF
erlinit: cmdline argc=1, merged argc=6
erlinit: merged argv[0]=/sbin/erlinit
erlinit: merged argv[1]=-v
erlinit: merged argv[2]=--hostname-pattern
erlinit: merged argv[3]=nerves-%.4s
erlinit: merged argv[4]=--uniqueid-exec
erlinit: merged argv[5]=/usr/bin/make-unique-id
erlinit: set_ctty
erlinit: find_erts_directory
erlinit: find_erts_library_directory
erlinit: directory /usr/lib/erlang/lib not found?
erlinit: find_release
erlinit: No release found in /srv/erlang.
erlinit: setup_environment
erlinit: setup_networking
erlinit: configure_hostname
erlinit: system_cmd '/usr/bin/make-unique-id'
erlinit: Hostname: nerves-0042
erlinit: Env: 'HOME=/root'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/usr/lib/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erl'
erlinit: Arg: 'erlexec'
erlinit: Launching erl...
Hello from erlexec
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: unmount_all
EOF
