#!/bin/sh

#
# Test whether the mount option works. We can't easily test
# that the mount works, so just make sure that it gets close.
#

$CAT >$CMDLINE_FILE <<EOF
-v --uid 100 --gid 200
EOF

$CAT >$EXPECTED <<EOF
erlinit: cmdline argc=6, merged argc=6
erlinit: merged argv[0]=/sbin/erlinit
erlinit: merged argv[1]=-v
erlinit: merged argv[2]=--uid
erlinit: merged argv[3]=100
erlinit: merged argv[4]=--gid
erlinit: merged argv[5]=200
erlinit: set_ctty
erlinit: find_erts_directory
erlinit: find_release
erlinit: No release found in /srv/erlang.
erlinit: setup_environment
erlinit: setup_networking
erlinit: configure_hostname
erlinit: /etc/hostname not found
erlinit: setting gid to 200
erlinit: setting uid to 100
erlinit: Env: 'HOME=/root'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/usr/lib/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erl'
erlinit: Arg: 'erlexec'
erlinit: Launching erl...
Hello from erlexec
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: unmount_all
EOF
