#!/bin/sh

#
# Test that the start_erl.data file that has contents that would
# fail the start_erl.data parser.
#

cat >$CMDLINE_FILE <<EOF
-v
EOF

RELEASE_PATH1=$WORK/srv/erlang/releases/0.0.1
RELEASE_PATH2=$WORK/srv/erlang/releases/0.0.2
RELEASE_PATH3=$WORK/srv/erlang/releases/0.0.3

for RPATH in $RELEASE_PATH1 $RELEASE_PATH2 $RELEASE_PATH3; do
    mkdir -p $RPATH
    touch $RPATH/a.boot
    touch $RPATH/b.boot
    touch $RPATH/c.boot
    touch $RPATH/d.boot
    touch $RPATH/sys.config
    touch $RPATH/vm.args
done

cat >$WORK/srv/erlang/releases/start_erl.data <<EOF
abcdefgh
EOF

cat >$EXPECTED <<EOF
erlinit: cmdline argc=2, merged argc=2
erlinit: merged argv[0]=/sbin/init
erlinit: merged argv[1]=-v
fixture: mount("proc", "/proc", "proc", 14, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mkdir("/dev/pts", 755)
fixture: mkdir("/dev/shm", 755)
fixture: mount("devpts", "/dev/pts", "devpts", 10, data)
erlinit: set_ctty
fixture: setsid()
fixture: mount("tmpfs", "/tmp", "tmpfs", 14, data)
fixture: mount("tmpfs", "/run", "tmpfs", 14, data)
erlinit: find_release
erlinit: /srv/erlang/releases/start_erl.data doesn't contain expected contents. Skipping.
erlinit: Using release in /srv/erlang/releases/0.0.3.
erlinit: find_sys_config
erlinit: find_vm_args
erlinit: find_boot_path
erlinit: Found more than one boot file. Using a.boot.
erlinit: find_erts_directory
erlinit: setup_environment
erlinit: setup_networking
fixture: ioctl(SIOCGIFFLAGS)
fixture: ioctl(SIOCSIFFLAGS)
fixture: ioctl(SIOCGIFINDEX)
erlinit: configure_hostname
erlinit: /etc/hostname not found
erlinit: Env: 'HOME=/root'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/srv/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erl'
erlinit: Arg: 'erlexec'
erlinit: Arg: '-config'
erlinit: Arg: '/srv/erlang/releases/0.0.3/sys.config'
erlinit: Arg: '-boot'
erlinit: Arg: '/srv/erlang/releases/0.0.3/a'
erlinit: Arg: '-args_file'
erlinit: Arg: '/srv/erlang/releases/0.0.3/vm.args'
erlinit: Launching erl...
Hello from erlexec
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: Sending SIGTERM to all processes
fixture: kill(-1, 15)
fixture: sleep(1)
erlinit: Sending SIGKILL to all processes
fixture: kill(-1, 9)
erlinit: unmount_all
erlinit: unmounting tmpfs at /sys/fs/cgroup...
fixture: umount("/sys/fs/cgroup")
erlinit: unmounting tmpfs at /dev/shm...
fixture: umount("/dev/shm")
erlinit: unmounting devpts at /dev/pts...
fixture: umount("/dev/pts")
erlinit: unmounting proc at /proc...
fixture: umount("/proc")
erlinit: unmounting sysfs at /sys...
fixture: umount("/sys")
EOF
