#!/bin/sh

#
# Test that the start_erl.data file that has contents that would
# fail the start_erl.data parser.
#

$CAT >$CMDLINE_FILE <<EOF
-v
EOF

RELEASE_PATH1=$WORK/srv/erlang/releases/0.0.1
RELEASE_PATH2=$WORK/srv/erlang/releases/0.0.2
RELEASE_PATH3=$WORK/srv/erlang/releases/0.0.3

for RPATH in $RELEASE_PATH1 $RELEASE_PATH2 $RELEASE_PATH3; do
    $MKDIR -p $RPATH
    $TOUCH $RPATH/a.boot
    $TOUCH $RPATH/b.boot
    $TOUCH $RPATH/c.boot
    $TOUCH $RPATH/d.boot
    $TOUCH $RPATH/sys.config
    $TOUCH $RPATH/vm.args
done

$CAT >$WORK/srv/erlang/releases/start_erl.data <<EOF
abcdefgh
EOF

$CAT >$EXPECTED <<EOF
erlinit: cmdline argc=2, merged argc=2
erlinit: merged argv[0]=/sbin/erlinit
erlinit: merged argv[1]=-v
erlinit: set_ctty
erlinit: find_erts_directory
erlinit: find_release
erlinit: /srv/erlang/releases/start_erl.data doesn't contain expected contents. Skipping.
erlinit: Using release in /srv/erlang/releases/0.0.3.
erlinit: find_sys_config
erlinit: find_vm_args
erlinit: find_boot_path
erlinit: Found more than one boot file. Using a.boot.
erlinit: setup_environment
erlinit: setup_networking
erlinit: configure_hostname
erlinit: /etc/hostname not found
erlinit: Env: 'HOME=/root'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/srv/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erl'
erlinit: Arg: 'erlexec'
erlinit: Arg: '-config'
erlinit: Arg: '/srv/erlang/releases/0.0.3/sys.config'
erlinit: Arg: '-boot'
erlinit: Arg: '/srv/erlang/releases/0.0.3/a'
erlinit: Arg: '-args_file'
erlinit: Arg: '/srv/erlang/releases/0.0.3/vm.args'
erlinit: Launching erl...
Hello from erlexec
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: unmount_all
EOF
