#!/usr/bin/env bash

#
# Test that saving a shutdown report works.
#
# Note: This only tests that the code runs and not that the report looks ok.
#

cat >"$CMDLINE_FILE" <<EOF
-v --shutdown-report /shutdown.txt
EOF

cat >$WORK/dev/kmsg <<EOF
5,0,0,-;Linux version 5.4.0-48-generic (buildd@lcy01-amd64-010) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 (Ubuntu 5.4.0-48.52-generic 5.4.60)
6,1,0,-;Command line: BOOT_IMAGE=/boot/vmlinuz-5.4.0-48-generic root=UUID=a4c0bdf3-a932-4867-bc25-b20b6f17a209 ro quiet splash vt.handoff=7
6,2,0,-;KERNEL supported cpus:
6,3,0,-;  Intel GenuineIntel
6,4,0,-;  AMD AuthenticAMD
6,5,0,-;  Hygon HygonGenuine
6,6,0,-;  Centaur CentaurHauls
6,7,0,-;  zhaoxin   Shanghai
6,8,0,-;x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
6,9,0,-;x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
3,1606,879450394488,-;igb 0000:06:00.0 enp6s0: Reset adapter
 SUBSYSTEM=pci
 DEVICE=+pci:0000:06:00.0
6,1607,879454003020,-;igb 0000:06:00.0 enp6s0: igb: enp6s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
 SUBSYSTEM=pci
 DEVICE=+pci:0000:06:00.0
3,1608,879474458726,-;igb 0000:06:00.0 enp6s0: Reset adapter
 SUBSYSTEM=pci
 DEVICE=+pci:0000:06:00.0
6,1609,879478078990,-;igb 0000:06:00.0 enp6s0: igb: enp6s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
 SUBSYSTEM=pci
 DEVICE=+pci:0000:06:00.0
5,1610,912127562742,-;audit: type=1400 audit(1601784002.044:53): apparmor="DENIED" operation="capable" profile="/usr/sbin/cups-browsed" pid=3673509 comm="cups-browsed" capability=23  capname="sys_nice"
EOF

RELEASE_PATH=$WORK/srv/erlang/releases/0.0.1
mkdir -p $RELEASE_PATH
touch $RELEASE_PATH/test.boot
touch $RELEASE_PATH/sys.config
touch $RELEASE_PATH/vm.args
ln -sf $FAKE_ERLEXEC.reboot $FAKE_ERTS_DIR/bin/erlexec

cat >"$EXPECTED" <<EOF
erlinit: cmdline argc=4, merged argc=4
erlinit: merged argv[0]=/sbin/init
erlinit: merged argv[1]=-v
erlinit: merged argv[2]=--shutdown-report
erlinit: merged argv[3]=/shutdown.txt
fixture: mount("proc", "/proc", "proc", 14, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 42, data)
fixture: mkdir("/dev/pts", 755)
fixture: mkdir("/dev/shm", 1777)
fixture: mount("devpts", "/dev/pts", "devpts", 10, data)
fixture: symlink("/dev/mmcblk0","/dev/rootdisk0")
fixture: symlink("/dev/mmcblk0p4","/dev/rootdisk0p4")
fixture: symlink("/dev/mmcblk0p3","/dev/rootdisk0p3")
fixture: symlink("/dev/mmcblk0p2","/dev/rootdisk0p2")
fixture: symlink("/dev/mmcblk0p1","/dev/rootdisk0p1")
erlinit: set_ctty
fixture: setsid()
fixture: mount("tmpfs", "/tmp", "tmpfs", 14, data)
fixture: mount("tmpfs", "/run", "tmpfs", 14, data)
erlinit: find_release
erlinit: /srv/erlang/releases/start_erl.data not found.
erlinit: Using release in /srv/erlang/releases/0.0.1.
erlinit: find_sys_config
erlinit: find_vm_args
erlinit: find_boot_path
erlinit: find_erts_directory
erlinit: setup_environment
erlinit: setup_networking
fixture: ioctl(SIOCGIFFLAGS)
fixture: ioctl(SIOCSIFFLAGS)
fixture: ioctl(SIOCGIFINDEX)
erlinit: configure_hostname
erlinit: /etc/hostname not found
fixture: mkdir("/root/seedrng", 700)
erlinit: Saving 256 bits of creditable seed for next boot
erlinit: Env: 'HOME=/home/user0'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=xterm-256color'
erlinit: Env: 'ROOTDIR=/srv/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erlexec'
erlinit: Env: 'RELEASE_SYS_CONFIG=/srv/erlang/releases/0.0.1/sys'
erlinit: Env: 'RELEASE_ROOT=/srv/erlang'
erlinit: Env: 'RELEASE_TMP=/tmp'
erlinit: Arg: 'erlexec'
erlinit: Arg: '-config'
erlinit: Arg: '/srv/erlang/releases/0.0.1/sys.config'
erlinit: Arg: '-boot'
erlinit: Arg: '/srv/erlang/releases/0.0.1/test'
erlinit: Arg: '-args_file'
erlinit: Arg: '/srv/erlang/releases/0.0.1/vm.args'
erlinit: Arg: '-boot_var'
erlinit: Arg: 'RELEASE_LIB'
erlinit: Arg: '/srv/erlang/lib'
erlinit: Launching erl...
erlexec is sending signal to reboot
erlinit: sigterm -> reboot
erlinit: waiting 10000 ms for graceful shutdown
erlinit: graceful shutdown detected
erlinit: kill_all
erlinit: Sending SIGTERM to all processes
fixture: kill(-1, 15)
fixture: sleep(1)
erlinit: Sending SIGKILL to all processes
fixture: kill(-1, 9)
erlinit: Writing shutdown report to '/shutdown.txt'
fixture: mkdir("/root/seedrng", 700)
erlinit: Seeding 256 bits and crediting
fixture: ioctl(RNDADDENTROPY)
erlinit: Saving 256 bits of creditable seed for next boot
erlinit: unmount_all
erlinit: unmounting tmpfs at /sys/fs/cgroup...
fixture: umount("/sys/fs/cgroup")
erlinit: unmounting tmpfs at /dev/shm...
fixture: umount("/dev/shm")
erlinit: unmounting devpts at /dev/pts...
fixture: umount("/dev/pts")
erlinit: unmounting proc at /proc...
fixture: umount("/proc")
erlinit: unmounting sysfs at /sys...
fixture: umount("/sys")
fixture: reboot(0x01234567)
EOF
