#!/bin/sh

#
# Test that the pivot root on an overlayfs feature "works"
#

cat >"$CMDLINE_FILE" <<EOF
-v --x-pivot-root-on-overlayfs
EOF

cat >"$EXPECTED" <<EOF
erlinit: cmdline argc=3, merged argc=3
erlinit: merged argv[0]=/sbin/init
erlinit: merged argv[1]=-v
erlinit: merged argv[2]=--x-pivot-root-on-overlayfs
erlinit: pivot_root_on_overlayfs
fixture: mount("", "/mnt", "tmpfs", 0, data)
fixture: mkdir("/mnt/.merged", 755)
fixture: mkdir("/mnt/.upper", 755)
fixture: mkdir("/mnt/.work", 755)
fixture: mount("", "/mnt/.merged", "overlay", 0, data)
fixture: mkdir("/mnt/.merged/dev", 755)
erlinit: Cannot create /mnt/.merged/dev
fixture: mount("/dev", "/mnt/.merged/dev", "tmpfs", 8192, data)
erlinit: Could not change directory to /mnt/.merged: No such file or directory
fixture: mount("proc", "/proc", "proc", 14, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 42, data)
fixture: mkdir("/dev/pts", 755)
fixture: mkdir("/dev/shm", 1777)
fixture: mount("devpts", "/dev/pts", "devpts", 10, data)
fixture: symlink("/dev/mmcblk0","/dev/rootdisk0")
fixture: symlink("/dev/mmcblk0p4","/dev/rootdisk0p4")
fixture: symlink("/dev/mmcblk0p3","/dev/rootdisk0p3")
fixture: symlink("/dev/mmcblk0p2","/dev/rootdisk0p2")
fixture: symlink("/dev/mmcblk0p1","/dev/rootdisk0p1")
erlinit: set_ctty
fixture: setsid()
fixture: mount("tmpfs", "/tmp", "tmpfs", 14, data)
fixture: mount("tmpfs", "/run", "tmpfs", 14, data)
erlinit: find_release
erlinit: No release found in /srv/erlang.
erlinit: find_erts_directory
erlinit: setup_environment
erlinit: setup_networking
fixture: ioctl(SIOCGIFFLAGS)
fixture: ioctl(SIOCSIFFLAGS)
fixture: ioctl(SIOCGIFINDEX)
erlinit: configure_hostname
erlinit: /etc/hostname not found
erlinit: Env: 'HOME=/home/user0'
erlinit: Env: 'PATH=/usr/sbin:/usr/bin:/sbin:/bin'
erlinit: Env: 'TERM=vt100'
erlinit: Env: 'ROOTDIR=/usr/lib/erlang'
erlinit: Env: 'BINDIR=/usr/lib/erlang/erts-6.0/bin'
erlinit: Env: 'EMU=beam'
erlinit: Env: 'PROGNAME=erlexec'
erlinit: Arg: 'erlexec'
erlinit: Arg: '-boot_var'
erlinit: Arg: 'RELEASE_LIB'
erlinit: Arg: '/srv/erlang/lib'
erlinit: Launching erl...
Hello from erlexec
erlinit: Erlang VM exited
erlinit: kill_all
erlinit: Sending SIGTERM to all processes
fixture: kill(-1, 15)
fixture: sleep(1)
erlinit: Sending SIGKILL to all processes
fixture: kill(-1, 9)
erlinit: unmount_all
erlinit: unmounting tmpfs at /sys/fs/cgroup...
fixture: umount("/sys/fs/cgroup")
erlinit: unmounting tmpfs at /dev/shm...
fixture: umount("/dev/shm")
erlinit: unmounting devpts at /dev/pts...
fixture: umount("/dev/pts")
erlinit: unmounting proc at /proc...
fixture: umount("/proc")
erlinit: unmounting sysfs at /sys...
fixture: umount("/sys")
EOF

