#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Frank Hunleth
#
# SPDX-License-Identifier: MIT
#

#
# Test that crumbs get logged to /dev/pmsg with verbosity off
#

cat >"$CMDLINE_FILE" <<EOF
EOF

cat >"$EXPECTED" <<EOF
fixture: mount("proc", "/proc", "proc", 14, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 42, data)
fixture: mkdir("/dev/pts", 755)
fixture: mkdir("/dev/shm", 1777)
fixture: mount("devpts", "/dev/pts", "devpts", 10, data)
fixture: symlink("/dev/mmcblk0","/dev/rootdisk0")
fixture: symlink("/dev/mmcblk0p4","/dev/rootdisk0p4")
fixture: symlink("/dev/mmcblk0p3","/dev/rootdisk0p3")
fixture: symlink("/dev/mmcblk0p2","/dev/rootdisk0p2")
fixture: symlink("/dev/mmcblk0p1","/dev/rootdisk0p1")
fixture: setsid()
fixture: mount("tmpfs", "/tmp", "tmpfs", 14, data)
fixture: mount("tmpfs", "/run", "tmpfs", 14, data)
erlinit: No release found in /srv/erlang.
fixture: ioctl(SIOCGIFFLAGS)
fixture: ioctl(SIOCSIFFLAGS)
fixture: ioctl(SIOCGIFINDEX)
erlinit: /etc/hostname not found
fixture: mkdir("/root/seedrng", 700)
Hello from erlexec
fixture: kill(-1, 15)
fixture: sleep(1)
fixture: kill(-1, 9)
fixture: mkdir("/root/seedrng", 700)
fixture: ioctl(RNDADDENTROPY)
fixture: umount("/sys/fs/cgroup")
fixture: umount("/dev/shm")
fixture: umount("/dev/pts")
fixture: umount("/proc")
fixture: umount("/sys")
fixture: reboot(0x01234567)
EOF

cat >"$PMSG_EXPECTED" <<EOF
2025-12-05T21:28:01.123456+00:00 erlinit Launching erl...
2025-12-05T21:28:01.123456+00:00 erlinit Intentional exit from Erlang: no
2025-12-05T21:28:01.123456+00:00 erlinit Erlang exit status: 0
2025-12-05T21:28:01.123456+00:00 erlinit Graceful shutdown succeeded: no
2025-12-05T21:28:01.123456+00:00 erlinit Graceful shutdown time: 0.000 s
2025-12-05T21:28:01.123456+00:00 erlinit Calling reboot(0x1234567)
EOF
