#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Frank Hunleth
#
# SPDX-License-Identifier: MIT
#

#
# Test that crumbs get logged to /dev/kmsg with verbosity off
#

cat >"$CMDLINE_FILE" <<EOF
EOF

cat >"$EXPECTED" <<EOF
fixture: mount("proc", "/proc", "proc", 14, data)
fixture: mount("sysfs", "/sys", "sysfs", 14, data)
fixture: mount("devtmpfs", "/dev", "devtmpfs", 42, data)
fixture: mkdir("/dev/pts", 755)
fixture: mkdir("/dev/shm", 1777)
fixture: mount("devpts", "/dev/pts", "devpts", 10, data)
fixture: symlink("/dev/mmcblk0","/dev/rootdisk0")
fixture: symlink("/dev/mmcblk0p4","/dev/rootdisk0p4")
fixture: symlink("/dev/mmcblk0p3","/dev/rootdisk0p3")
fixture: symlink("/dev/mmcblk0p2","/dev/rootdisk0p2")
fixture: symlink("/dev/mmcblk0p1","/dev/rootdisk0p1")
fixture: setsid()
fixture: mount("tmpfs", "/tmp", "tmpfs", 14, data)
fixture: mount("tmpfs", "/run", "tmpfs", 14, data)
fixture: ioctl(SIOCGIFFLAGS)
fixture: ioctl(SIOCSIFFLAGS)
fixture: ioctl(SIOCGIFINDEX)
fixture: mkdir("/root/seedrng", 700)
Hello from erlexec
fixture: kill(-1, 15)
fixture: sleep(1)
fixture: kill(-1, 9)
fixture: mkdir("/root/seedrng", 700)
fixture: ioctl(RNDADDENTROPY)
fixture: umount("/sys/fs/cgroup")
fixture: umount("/dev/shm")
fixture: umount("/dev/pts")
fixture: umount("/proc")
fixture: umount("/sys")
fixture: reboot(0x01234567)
EOF

cat >"$KMSG_EXPECTED" <<EOF
<28>erlinit: No release found in /srv/erlang.
<28>erlinit: /etc/hostname not found
EOF
