#!/bin/sh

#
# Test that specifying -v in the config file works
#

$CAT >$CONFIG <<EOF
-v
EOF

$CAT >$EXPECTED <<EOF
erlinit: Starting erlinit...
erlinit: cmdline argc=1, merged argc=2
erlinit: merged argv[0]=/sbin/erlinit
erlinit: merged argv[1]=-v
erlinit: Could not mount tmpfs in /tmp: Operation not permitted
Check that tmpfs support is enabled in the kernel config.
EOF
